
POST https://node-beginner.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node testeeee ",
    "description": "santana",
    "duration": 777
}


###

GET https://node-beginner.onrender.com/videos


###

PUT https://node-beginner.onrender.com/videos/dc447da1-ee4f-4d71-b202-e33f543b66a6
Content-Type: application/json

{
    "title": "Lucas Santana Belato",
    "description": "Alterado 2",
    "duration": 777
}

###

DELETE  https://node-beginner.onrender.com/videos/dc447da1-ee4f-4d71-b202-e33f543b66a6
